# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 722f6750ede62afd4dddf5f30bc117953409bfa4c76ae94a6c22f99584125879298fb604279620153e3fe60849fa095590db56d53b75821228d62255bdd58eed

test:
  secret_key_base: a88396b6d6bb632604989e18e5e844802376bed4fc5f4c06ade4bf89c9230f5127ec71281c95e3b4139fbdbb57093b666b882422862669057da04b1ec3345e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
